[package]
name = "guess_game"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.2" # 随机数生成
crossterm = "0.26"       # 彩色文字、光标控制
indicatif = "0.17" 
eframe = "0.33"       # egui 官方推荐的桌面应用框架
egui = "0.33"